<?xml version="1.0" encoding="UTF-8"?>
<testrun name="MapTest" project="ElementalTowerDefense" tests="6" started="6" failures="0" errors="1" ignored="0">
  <testsuite name="MapTest" time="0.003">
    <testcase name="testThatMapWontAcceptTwoTowersAtTheSameSpot" classname="MapTest" time="0.002"/>
    <testcase name="testPathDoesNotGoBackOnItself" classname="MapTest" time="0.0"/>
    <testcase name="testThatPathStaysInBoundaries" classname="MapTest" time="0.0"/>
    <testcase name="testThatMapCanGenerateEnemies" classname="MapTest" time="0.001">
      <error>java.lang.NoSuchMethodError: Frame$element.values()[LFrame$element;
	at Map.$SWITCH_TABLE$Frame$element(Map.java:13)
	at Map.generateEnemy(Map.java:85)
	at MapTest.testThatMapCanGenerateEnemies(MapTest.java:103)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:73)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:46)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:180)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:41)
	at org.junit.runners.ParentRunner$1.evaluate(ParentRunner.java:173)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:220)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:46)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
    <testcase name="testPathGenerationIsRandom" classname="MapTest" time="0.0"/>
    <testcase name="testThatMapCanAcceptNewTower" classname="MapTest" time="0.0"/>
  </testsuite>
</testrun>
